### PR TITLE
Update: Initial content

### PR DESCRIPTION
**Pull request by prerana1821**
Updated Content

### CODE REVIEW

**Comment by srivcodes** [comment]
@gkanishk Please accept the pr

**Comment by gkanishk** [comment]
> @gkanishk Please accept the pr

@SriV-dya is the app working locally? This show page not found inside [deployment](https://deploy-preview-1--fmneogdev.netlify.app/) preview

**Comment by srivcodes** [comment]
@gkanishk I'll just check that!

**Comment by gkanishk** [comment]
try to create a build if everything works fine

**Comment by gkanishk** [comment]
@tanaypratap we need to change Netify's build configurations like `build command` as initially repo was HTML based and now it's codebase is Gatsby based.
Here's the test deployment [link](https://fm-neog-demo.netlify.app/) which @prerana1821 has hosted.

**Comment by tanaypratap** [comment]
Ack. I'll change it and reply here.

**Comment by gkanishk** [comment]
Merged inside #2

**Pull request closed without merging**
